[package]
name = "ast2str-lib"
version = "0.1.0"
authors = ["OptimalStrategy <17456182+OptimalStrategy@users.noreply.github.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
pretty_assertions = "0.7.2"
